### ISSUE TITLE
[Transformation] Damned

### ISSUE THREAD

**Issue by jtmcginnis** [FacemanFoothand/abpack2#114]
Gain flying + demon form

Removes ALL health, gives twelve black hearts, Grants one life. On death (this will only happen once) you respawn and activate the forget me now effect

Art: Not Started

Code: In Progress

**Comment by jtmcginnis** [comment]
Possible Damned Pool: Gloom Skull, Chalice of Blood, Abyss, Birth Control, Empty Vessel, Cambion Conception

**Comment by FacemanFoothand** [comment]
3 of these, grants the Damned transfo: Gloom Skull, Chalice of Blood, Pentagram, The Mark, Contract From Below and The Pact
