### ISSUE TITLE
[All That Is Unholy] Challenges

### ISSUE THREAD

**Issue by FacemanFoothand** [FacemanFoothand/abpack2#184]
Challenge: New Friends
Rules: Blooderfly + Spirit Eye + Infested Baby (Any other familiars?)
Status: 

Challenge: H4ck3r
Rules: Aimbot + Soy Milk + Spectral Tears
Status: 

Challenge: Restless Leg Syndrome
Rules: Hot Coals, if the player stands still for a few frames Spawn Troll Bomb
Status: 

Challenge: Empty
Rules: Void + Abyss + only actives can appear
Status: 

Challenge: The Collector
Rules: Cauldron + Hoarder
Status: 

Challenge: I5:44c 2000
Rules: Cyborg Transformation(including Tech Alpha), no item rooms
Status: 

Challenge: For the Hoard!
Rules: Hoarder + Bum friend + Key beggar (with MAX luck)
Status: 

Challenge: Electric Avenue
Rules: Ludovico Technique + Quad Shot + Inner Eye + 20/20 + Soy Milk + Tech Alpha + Rubber Cement
Status:

**Comment by Meowlala** [comment]
All implemented!
